-- Migration: Add Sessions and Environment Capsules
-- Date: 2025-01-08
-- Description: Adds new tables for sessions and environment capsules to support the new V8 model
-- IMPORTANT: Copy this entire SQL and paste it into Supabase Studio SQL Editor, then click "Run"

-- ============================================================================
-- 1. CREATE NEW TABLES FIRST
-- ============================================================================

-- Sessions table: Represents a session within a stage
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id BIGINT NOT NULL REFERENCES public.stages(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    session_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Session structure table: Represents the sport structure/steps of a session
CREATE TABLE IF NOT EXISTS public.session_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL,
    step_title TEXT NOT NULL,
    step_duration_minutes INTEGER,
    step_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Environment capsules table: Reusable environment education modules
CREATE TABLE IF NOT EXISTS public.environment_capsules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    duration_minutes INTEGER,
    level TEXT,
    created_by TEXT NOT NULL,
    is_public BOOLEAN DEFAULT FALSE,
    activity_types TEXT[] DEFAULT '{}',
    location_types TEXT[] DEFAULT '{}',
    themes TEXT[] DEFAULT '{}',
    season TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Capsule content table: Individual content items within a capsule
CREATE TABLE IF NOT EXISTS public.capsule_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capsule_id BIGINT NOT NULL REFERENCES public.environment_capsules(id) ON DELETE CASCADE,
    content_type TEXT NOT NULL,
    content_data JSONB NOT NULL,
    content_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Session capsules table: Links sessions to capsules with optional customizations
CREATE TABLE IF NOT EXISTS public.session_capsules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    capsule_id BIGINT NOT NULL REFERENCES public.environment_capsules(id) ON DELETE CASCADE,
    session_step_id BIGINT REFERENCES public.session_structure(id) ON DELETE SET NULL,
    capsule_order INTEGER NOT NULL,
    custom_modifications JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ============================================================================
-- 3. CREATE INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_sessions_stage_id ON public.sessions(stage_id);
CREATE INDEX IF NOT EXISTS idx_session_structure_session_id ON public.session_structure(session_id);
CREATE INDEX IF NOT EXISTS idx_environment_capsules_created_by ON public.environment_capsules(created_by);
CREATE INDEX IF NOT EXISTS idx_environment_capsules_is_public ON public.environment_capsules(is_public);
CREATE INDEX IF NOT EXISTS idx_capsule_content_capsule_id ON public.capsule_content(capsule_id);
CREATE INDEX IF NOT EXISTS idx_session_capsules_session_id ON public.session_capsules(session_id);
CREATE INDEX IF NOT EXISTS idx_session_capsules_capsule_id ON public.session_capsules(capsule_id);

-- ============================================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_structure ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.environment_capsules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.capsule_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_capsules ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. CREATE RLS POLICIES (Public access - same as other tables)
-- ============================================================================

CREATE POLICY "Public access for select" ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Public access for insert" ON public.sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public access for update" ON public.sessions FOR UPDATE USING (true);
CREATE POLICY "Public access for delete" ON public.sessions FOR DELETE USING (true);

CREATE POLICY "Public access for select" ON public.session_structure FOR SELECT USING (true);
CREATE POLICY "Public access for insert" ON public.session_structure FOR INSERT WITH CHECK (true);
CREATE POLICY "Public access for update" ON public.session_structure FOR UPDATE USING (true);
CREATE POLICY "Public access for delete" ON public.session_structure FOR DELETE USING (true);

CREATE POLICY "Public access for select" ON public.environment_capsules FOR SELECT USING (true);
CREATE POLICY "Public access for insert" ON public.environment_capsules FOR INSERT WITH CHECK (true);
CREATE POLICY "Public access for update" ON public.environment_capsules FOR UPDATE USING (true);
CREATE POLICY "Public access for delete" ON public.environment_capsules FOR DELETE USING (true);

CREATE POLICY "Public access for select" ON public.capsule_content FOR SELECT USING (true);
CREATE POLICY "Public access for insert" ON public.capsule_content FOR INSERT WITH CHECK (true);
CREATE POLICY "Public access for update" ON public.capsule_content FOR UPDATE USING (true);
CREATE POLICY "Public access for delete" ON public.capsule_content FOR DELETE USING (true);

CREATE POLICY "Public access for select" ON public.session_capsules FOR SELECT USING (true);
CREATE POLICY "Public access for insert" ON public.session_capsules FOR INSERT WITH CHECK (true);
CREATE POLICY "Public access for update" ON public.session_capsules FOR UPDATE USING (true);
CREATE POLICY "Public access for delete" ON public.session_capsules FOR DELETE USING (true);

-- ============================================================================
-- 6. ALTER EXISTING TABLES (after new tables are created)
-- ============================================================================

ALTER TABLE public.stages
ADD COLUMN IF NOT EXISTS sport_activity TEXT,
ADD COLUMN IF NOT EXISTS sport_level TEXT,
ADD COLUMN IF NOT EXISTS sport_description TEXT;

ALTER TABLE public.stages_exploits
ADD COLUMN IF NOT EXISTS session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- All tables created successfully!
-- You can now use the capsules feature in the application.

