-- Create stage_objectives_completion table to track completed objectives per stage
CREATE TABLE IF NOT EXISTS public.stage_objectives_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id BIGINT NOT NULL REFERENCES public.stages(id) ON DELETE CASCADE,
    objective_id TEXT NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(stage_id, objective_id)
);

-- Enable Row Level Security
ALTER TABLE public.stage_objectives_completion ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (demo mode - adjust for production)
CREATE POLICY "Public access for select" ON public.stage_objectives_completion 
    FOR SELECT USING (true);

CREATE POLICY "Public access for insert" ON public.stage_objectives_completion 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Public access for update" ON public.stage_objectives_completion 
    FOR UPDATE USING (true);

CREATE POLICY "Public access for delete" ON public.stage_objectives_completion 
    FOR DELETE USING (true);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_stage_objectives_completion_stage_id 
    ON public.stage_objectives_completion(stage_id);

CREATE INDEX IF NOT EXISTS idx_stage_objectives_completion_objective_id 
    ON public.stage_objectives_completion(objective_id);

