-- Create session_step_completion table to track completed steps per session
CREATE TABLE IF NOT EXISTS public.session_step_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    step_id BIGINT NOT NULL REFERENCES public.session_structure(id) ON DELETE CASCADE,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(session_id, step_id)
);

-- Enable Row Level Security
ALTER TABLE public.session_step_completion ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (demo mode - adjust for production)
CREATE POLICY "Public access for select" ON public.session_step_completion 
    FOR SELECT USING (true);

CREATE POLICY "Public access for insert" ON public.session_step_completion 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Public access for delete" ON public.session_step_completion 
    FOR DELETE USING (true);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_session_step_completion_session_id 
    ON public.session_step_completion(session_id);

CREATE INDEX IF NOT EXISTS idx_session_step_completion_step_id 
    ON public.session_step_completion(step_id);

