-- Create stage_game_history table to track game results per stage
CREATE TABLE IF NOT EXISTS public.stage_game_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    stage_id BIGINT NOT NULL REFERENCES public.stages(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    total INTEGER NOT NULL,
    percentage INTEGER NOT NULL,
    results JSONB NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.stage_game_history ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (demo mode - adjust for production)
CREATE POLICY "Public access for select" ON public.stage_game_history 
    FOR SELECT USING (true);

CREATE POLICY "Public access for insert" ON public.stage_game_history 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Public access for update" ON public.stage_game_history 
    FOR UPDATE USING (true);

CREATE POLICY "Public access for delete" ON public.stage_game_history 
    FOR DELETE USING (true);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_stage_game_history_stage_id 
    ON public.stage_game_history(stage_id);

CREATE INDEX IF NOT EXISTS idx_stage_game_history_game_id 
    ON public.stage_game_history(game_id);

CREATE INDEX IF NOT EXISTS idx_stage_game_history_created_at 
    ON public.stage_game_history(created_at DESC);

